# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('videoId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('channelId', models.CharField(max_length=50)),
                ('title', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
