# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20151230_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
